name: action workflow
on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps: 
            -   name: simple javascrpit actions
                id: hello
                uses: actions/hello-world-javascript-action@main
                with:
                    who-to-greet: 'Mona the Octocat'
            -   name: get the outputname
                run: echo "${{steps.hello.outputs.time}}"
            